[build]
  base = "catechize/"
  command = "npm run build"
  publish = "dist"

[build.environment]
  NODE_VERSION = "18"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[dev]
  framework = "nuxt"
  targetPort = 3000

[functions]
  directory = "netlify/functions"
