[build]
  base = "catechize/"
  command = "./netlify.sh"
  publish = "dist"

[build.environment]
  NODE_VERSION = "18"

# Block PHP files and common PHP attack patterns
[[redirects]]
  from = "/*.php"
  to = "/404.html"
  status = 404
  force = true

[[redirects]]
  from = "/index.php"
  to = "/404.html"
  status = 404
  force = true

[[redirects]]
  from = "/*/index.php"
  to = "/404.html"
  status = 404
  force = true

[[redirects]]
  from = "/*.php?*"
  to = "/404.html"
  status = 404
  force = true

# SPA catch-all rule (must be last)
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[dev]
  framework = "nuxt"
  targetPort = 3000

[functions]
  directory = "netlify/functions"
